version: '3.9'

services:

  geoserver:
    image: lapierre/geoserver:${IMAGE_VERSION}
    ports:
      - "8080:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
    volumes:
      - geoserver_data:/opt/geoserver_data/
#      - ./additional_libs:/opt/additional_libs # by mounting this we can install libs from host on startup

volumes:
  geoserver_data:
